Fixed markdown of rspec_api_documentation
edymerchk/awesome-ruby-api pull request #18
Opened 2017-10-26 06:30 UTC by eshaiju

2017-10-26 15:40 UTC, edymerchk requested changes

2017-10-26 15:40 UTC, edymerchk commented on README.md
> +* [rspec_api_documentation](https://github.com/zipmark/rspec_api_documentation) - RSpec API Doc Generator
can you add a dot at the end ?

2017-10-27 08:32 UTC, eshaiju commented
@edymerchk Updated

2017-10-28 15:20 UTC, merged

2017-10-28 15:20 UTC, edymerchk commented
thanks @eshaiju !